### ISSUE TITLE
MELPA badge, please

### ISSUE THREAD

**Issue by Boruch-Baum** [fourier/loccur#13]
I discovered this repository via emacswiki, and before installing it directly, I double-checked and see that it's available via MELPA (and gnu v1.2.4 ?). Melpa makes available a 'badge' for each of its packages that you can add to your README with the benefit to users that they can install and manage the package totally within emacs (and that you've been 'approved' by MELPA. For package `loccur`, see: https://melpa.org/#/loccur

There, the badge for a markdown-mode file is:
```
[![MELPA](https://melpa.org/packages/loccur-badge.svg)](https://melpa.org/#/loccur)
```

For an example of it in use, see: https://github.com/Boruch-Baum/emacs-diredc

**Comment by fourier** [comment]
Added, thanks.
