### ISSUE TITLE
Question / feature request

### ISSUE THREAD

**Issue by carlcotner** [fourier/loccur#5]
First of all, I really appreciate that you made and released this. loccur is great! :-)

My question is: why does loccur leave a blank line at the top and bottom of the folded file? (Perhaps there could be an option to change that behavior?)

I don't know if you are familiar with the XEDIT editor on VM/CMS (now z/VM, I believe), but it had an "ALL" command that did the same thing and was invaluable.

**Comment by fourier** [comment]
Thanks for reporting this, I've seen it but never actually thought about fixing it.
