### ISSUE TITLE
interactive mode extension

### ISSUE THREAD

**Issue by carlcotner** [fourier/loccur#6]
There is a code snippet at

[http://www.randomsample.de/dru5/node/78](http://www.randomsample.de/dru5/node/78)

to make loccur interactive by extending isearch with hooks. Unfortunately the code doesn't quite work anymore, but it does with a small change:

```
(add-hook 'isearch-update-post-hook
          (lambda ()
            (let ((loccur-mode nil))
              (loccur (regexp-quote isearch-string)))))

(add-hook 'isearch-mode-end-hook
          (lambda ()
            (loccur nil)))
```

Could this code snippet be added to the documentation and/or the functionality added to loccur as an option?

**Comment by fourier** [comment]
Thanks, added to the end of the README.md file in **Tips and tricks** section. Works for me.
