### ISSUE TITLE
Bug when repeating loccur-current

### ISSUE THREAD

**Issue by bymoz089** [fourier/loccur#8]
When repeating `loccur-current` without moving point, loccur is not working as expected.

**Steps:**
1. start Emacs with `emacs -Q`
2. initialize Emacs with `(require 'package)`, `(package-initialize)` and `(require 'loccur)`
3. put point on a word in current buffer
4. call `M-x loccur-current`
5. call `M-x loccur-mode` to quit loccur
6. call `M-x loccur-current` again
Remark: do not move point in between, i.e. use `loccur-current` on the same word.

**expected behavior:**
After step 6, loccur-mode is supposed to be enabled and buffer should only show matching lines (like it did after step 4).

**current behavior:**
Nothing happens after step 6. loccur-mode is not enabled and buffer shows same view as **before** step 6.

**used test system:**
Tested with emacs 25.1.1., Linux

**Comment by fourier** [comment]
Try now, should be fixed.

**Comment by fourier** [comment]
Ok ill close it for now.
