### ISSUE TITLE
permit user to choose not to have (current-word) as loccur-prompt fallback

### ISSUE THREAD

**Issue by titaniumbones** [fourier/loccur#9]
I've customized my loccur-prompt this  way:

```emacs-lisp

(defvar loccur-fill-word nil
          "whether or not to fill in the current word at prompt")

(defun loccur-prompt ()
  "Return the default value of the prompt.
Default value for prompt is a current word or active region(selection),
if its size is 1 line"
  (let ((prompt
         (if (and transient-mark-mode
                  mark-active)
             (let ((pos1 (region-beginning))
                   (pos2 (region-end)))
               ;; Check if the start and the end of an active region is on
               ;; the same line
               (when (save-excursion
                       (goto-char pos1)
                       (<= pos2 (line-end-position)))
                   (buffer-substring-no-properties pos1 pos2)))
           (if loccur-fill-word 
               (current-word) nil))))
    prompt))
```
This seems like hte right way for users (like me) who also have a keybinding for loccur-current.  I haven't forked the rpo yet but if you're interested I can make a PR with a more formal patch.  Or you can just implement yrself if you prefer!

**Comment by titaniumbones** [comment]
or of course you can decide this is a bad idea :-)

**Comment by fourier** [comment]
I've implemented the new solution for this, without introducing a new variable.
You just need to call loccur with the universal prefix, i.e. C-u M-x loccur or via something like this
```lisp
(defun loccur-no-selection ()
  (interactive)
    (let ((current-prefix-arg 1))
        (call-interactively
             'loccur)))
```

**Comment by fourier** [comment]
@titaniumbones will it work for you? Or you have some specific scenario.

**Comment by fourier** [comment]
You don't need to keep your solution. You can just add function I've written above `loccur-no-selection` to your configuration and just bind it to something, i.e. Ctrl-o or so.

**Comment by fourier** [comment]
Closing as it is implemented.

**Comment by titaniumbones** [comment]
thank you @fourier !
